stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    outs:
    - bottleneck_features_train.npy
    - bottleneck_features_validation.npy
    - model.pth
    metrics:
    - metrics.csv:
        cache: false
